import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  topBarContainer:{
    paddingLeft:10,
    backgroundColor:'white',
    height:75,
  },
  textSlim:{
    fontWeight:"normal",

  },
  textBold:{
    fontWeight:"bold",
    color:'#212a42',
    fontSize:15,
  },
  topbarIcons:{
    flexDirection:'row',
    alignItems:'center',
  },
  textIcon:{
    width:250,
    fontSize:11,
    color:'#212a42',
    marginTop:1.5,
    marginLeft:5
  },
  cardContainer:{
    flexDirection:'row',
    flex:1,
    padding:8,
    alignItems:'center',
    justifyContent:'center',
  },
  imageContainer:{
    flex:1,
    zIndex:1,
    height:85,
    backgroundColor:'#438a5e',
    borderRadius:20,
    alignItems:'center',
    justifyContent:'center',
    elevation: 3,
  },
  cardImage:{
    resizeMode:'contain',
    height:75,
    width:80,
  },
  textContainer:{
    flex:3.5,
    flexDirection:'row',
    backgroundColor:'#f5f5f5',
    height:80,
    marginLeft:-10,
    elevation: 2,
    borderTopEndRadius:8,
    borderBottomEndRadius:8,
  },
  textRow:{
    flex:7,
    paddingLeft:18
  },
  headerCard:{
    fontSize:13,
    color:'#212a42',
    fontWeight:'bold'
  },
  textContent:{
    marginRight:10,
    marginTop:2,
    fontSize:10,
    textAlign:"justify",
  },
  countRow:{
    flex:1.5,
    alignItems:"flex-end",
    borderTopEndRadius:8,
    borderBottomEndRadius:8,
  },
  counterContainer:{
    backgroundColor:'#e4e3e3',
    borderTopEndRadius:8,
    borderBottomEndRadius:8,
    flexDirection:'column',
    elevation:2,
  },
  itemRow:{
    flex:1,
    width:40,
    alignItems:'center',
    justifyContent:"center",
  },
  textDark:{
    color:'#212a42',
  },
  subtotalContainer:{
    flexDirection:'row',
    justifyContent:"space-between",
    padding:8,
    borderTopColor:'#e4e3e3',
    borderTopWidth:1.5,
    backgroundColor:'#006dff'
  },
  footerContainer:{
    height:25,
    backgroundColor:'#006dff'
  },
  textTotal:{
    fontWeight:"bold",
    color:'white',
    textDecorationLine:'underline'
  },
  price:{
    marginTop:10,
    fontSize:12,
    color:'#ff5e00',
    fontWeight:'bold'
  }
});

export default styles;