import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  topBarContainer:{
    paddingLeft:10,
    backgroundColor:'white',
    height:75,
  },
  textSlim:{
    fontWeight:"normal",
  },
  textBold:{
    fontWeight:"bold",
    color:'#212a42',
    fontSize:15,
  },
  topbarIcons:{
    flexDirection:'row',
    alignItems:'center',
  },
  textIcon:{
    width:250,
    fontSize:11,
    color:'#212a42',
    marginTop:1.5,
    marginLeft:5
  },
  cardContainer:{
    flexDirection:'row',
    flex:1,
    backgroundColor:'white',
    margin:10,
    height:95,
    borderRadius:8,
    elevation:3,
  },
  imageContainer:{
    flex:2.8,
  },
  cardImage:{
    flex:1,
    resizeMode:'contain',
  },
  textContainer:{
    padding:5,
    flex:7,
    flexDirection:'column',
  },
  headerCard:{
    fontSize:16,
    color:'#212a42',
    fontWeight:'bold'
  },
  textContent:{
    marginRight:3,
    marginTop:2,
    fontSize:10,
    textAlign:"justify",
  },
  counterContainer:{
    flex:1.6,
    flexDirection:'column',
    borderLeftColor:'#f5f5f5',
    borderLeftWidth:3,
  },
  itemRow:{
    flex:1,
    alignItems:'center',
    justifyContent:"center",
  },
  textDark:{
    color:'#212a42',
  },
  subtotalContainer:{
    flexDirection:'row',
    justifyContent:"space-between",
    padding:8,
    borderTopColor:'#e4e3e3',
    borderTopWidth:1.5,
    backgroundColor:'#006dff'
  },
  footerContainer:{
    height:25,
    backgroundColor:'#006dff'
  },
  textTotal:{
    fontWeight:"bold",
    color:'white',
    textDecorationLine:'underline'
  },
  price:{
    marginTop:3,
    fontSize:14,
    color:'#212a42',
    fontWeight:'bold'
  },
  gratis:{
    marginTop:3,
    fontSize:14,
    color:'#db6400',
    fontWeight:'bold'
  }
});

export default styles;