import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  topBarContainer:{
    paddingLeft:10,
    backgroundColor:'#f0a500',
    height:75,
  },
  textSlim:{
    fontWeight:"normal",
  },
  textBold:{
    fontWeight:"bold",
    color:'white',
    fontSize:15,
  },
  topbarIcons:{
    flexDirection:'row',
    alignItems:'center',
  },
  textIcon:{
    fontSize:11,
    color:'white',
    marginLeft:5
  },
  cardContainer:{
    flexDirection:'row',
    flex:1,
    padding:8,
    alignItems:'center',
    justifyContent:'center',
  },
  imageContainer:{
    flex:1,
    zIndex:1,
    height:80,
    backgroundColor:'#438a5e',
    borderRadius:20,
    alignItems:'center',
    justifyContent:'center',
    elevation: 3,
  },
  cardImage:{
    resizeMode:'contain',
    height:75,
    width:80,
  },
  textContainer:{
    flex:3.5,
    flexDirection:'row',
    backgroundColor:'#f5f5f5',
    height:60,
    marginLeft:-5,
    borderTopEndRadius:3,
    borderBottomEndRadius:3,
    elevation: 3,
  },
  textRow:{
    flex:7,
    paddingLeft:10
  },
  headerCard:{
    fontSize:13,
  },
  textContent:{
    marginTop:2,
    fontSize:10,
    textAlign:"justify",
  },
  countRow:{
    flex:3.5,
    alignItems:"center",
    justifyContent:"center",
    paddingTop:8,
  },
  counterContainer:{
    backgroundColor:'#e4e3e3',
    borderRadius:10,
    flexDirection:'row',
    width:75,
    elevation:2,
  },
  itemRow:{
    flex:1,
    alignItems:'center',
    justifyContent:"center",
  },
  textDark:{
    color:'#363636',
  },
  subtotalContainer:{
    flexDirection:'row',
    justifyContent:"space-between",
    padding:8,
    borderTopColor:'#e4e3e3',
    borderTopWidth:1.5,
  },
  footerContainer:{
    height:25,
    backgroundColor:'#f0a500'
  },
  textTotal:{
    fontWeight:"bold",
    color:'#111d5e'
  }
});

export default styles;