import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  bottomBar:{
    padding:10,
    height:400,
    elevation:10,
    backgroundColor:'white'
  },
  switchRow:{
    marginTop:15,
    marginBottom:15,
    flexDirection:'row'
  },
  switchContainer:{
    flex:1,
    flexDirection:'row',
    justifyContent:"center",
    alignItems:"center"
  },
  containerCards:{
    marginTop:5,
    marginLeft:10,
    marginRight:10,
    height:300,
  },
  textSwitchContainer:{
    flex:0.5,
    justifyContent:"center"
  },
  buttonSwitch:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:'#ff5e00',
    paddingBottom:8,
    paddingTop:8,
    paddingRight:15,
    paddingLeft:15,
    marginRight:10,
    borderRadius:20,
    height:35,
    width:110
  },
  aclaracionInput:{
    marginTop:15,
    paddingLeft:10,
    borderColor:'gray',
    borderWidth:1,
    borderRadius:20,
  },
  cardContainer:{
    height:60,
    flexDirection:'row',
    flex:1,
    backgroundColor:'white',
    alignItems:'center',
    justifyContent:'center',
    borderRadius:8,
    marginBottom:8,
    marginLeft:5,
    marginRight:5,
    marginTop:8,
    elevation:3,
  },
  imageContainer:{
    flex:0.8,
    alignItems:'center',
    justifyContent:'center',
  },
  cardImage:{
    resizeMode:'contain',
    height:55,
    width:55,
  },
  textContainer:{
    flex:3.5,
    flexDirection:'row',
  },
  quantityRow:{
    flex:2,
    alignItems:'center',
    justifyContent:'center',
  },
  textRow:{
    flex:7,
    paddingLeft:15,
    justifyContent:"center"
  },
  itemRow:{
    flex:1,
    alignItems:'center',
    justifyContent:"center",
  },
  textDark:{
    color:'#212a42',
  },
  footerContainer:{
    height:25,
    backgroundColor:'#f0a500'
  },
  waIcon:{
    resizeMode:'contain',
    height:70,
    width:70,
  },
  waText:{
    fontSize:10,
    color:'#212a42'
  }
});

export default styles;